# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: MyEtherWallet Knowledge Base
subtitle:
description: MyEtherWallet Knowledge Base
keywords: ethereum
author: MyEtherWallet.com
language:
  - en
  - ru
timezone: America/Los_Angeles

i18n:
  languages: [en, ru]
#  type: [page, post]
  generator: [index]

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://localhost.com
url: https://kb.myetherwallet.com/
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  single_language_index: false

# Extensions
exclude_generator:
  - index
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: mew5
theme_config: ./themes/_config.yml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:MyEtherWallet/knowledge-base-v5.git


alias:
  /offline/is-the-send-page-offline.html: /
  /offline/ethereum-cold-storage-with-myetherwallet.html: /
  /diving-deeper/readme.html: /
  /diving-deeper/getting-thru-the-shit-times.html: /
  /ens/importing-ens-bid-created-on-myetherwallet-metamask.html: /
  /ens/manually-revealing-ens-bids-hard.html: /
  /ens/starting-an-ens-auction-without-bidding.html: /
  /ens/ens-what-to-do-if-you-forgot-your-bid.html: /
  /ens/ens-brute-forcing-secret-word-phrases.html: /
  /ens/why-the-ens-bid-process-is-so-complicated.html: /
  /faq/check-the-current-eth-block-number.html: /
  /faq/couldnt-everybody-put-in-a-random-key-and-send-to-own-address.html: /
  /faq/unlocking-keystore-file-freezes-browser.html: /
  /faq/buying-selling-exchanging-eth-tokens-fiat.html: /
  /faq/how-to-buy-ethereum-with-usd.html: /
  /gas/how-to-set-gas-price-above-limits.html: /
  /hardware-wallets/trezor-sending-to-trezor-device.html: /
  /hardware-wallets/accidentally-connecting-to-hardware-wallet-on-phishing-site.html: /
  /hardware-wallets/multiple-addresses-on-hardware-wallet.html: /
  /hardware-wallets/hardware-wallet-recommendations.html: /
  /networks/access-your-expanse-on-myetherwallet.html: /
  /networks/access-your-etc-on-myetherwallet.html: /
  /faq/ethereum-balance-not-loading-or-showing.html: /
  /faq/why-dont-you-make-me-move-my-mouse-to-generate-seed.html: /
  /faq/withdrawing-dao-tokens.html: /
  /hardware-wallets/ledger-hardware-wallet-missing-characters-from-address.html: /
  /security/turning-of-2fa-on-myetherwallet.html: /
  /hardware-wallets/using-myetherwallet-with-ledger-nano-s.html: /
  /hardware-wallets/backing-up-trezor-myetherwallet.html: /
  /security/restoring-access-to-your-accounts-if-lose-device-with-2fa.html: /
  /security/call-to-action-help-us-with-phishers-please.html: /
  /security/advanced-secure-wallets-by-tomshwom.html: /
  /security/how-to-securely-store-and-guard-your-private-key.html: /
  /hardware-wallets/trezor-hardware-wallet-sending-from-trezor.html: /
  /diving-deeper/announcement-history.html: /
  /diving-deeper/links-you-should-read-next.html: /
  /diving-deeper/ethereum-list-of-support-and-communities.html: /
  /diving-deeper/developing-myetherwallet.html: /
  /addresses/ethereum-account-not-showing-on-blockchain.html: /
  /getting-started/myetherwallet-help-and-quicktips.html: /
  /getting-started/protecting-yourself-and-your-funds.html: /
  /getting-started/myetherwallet-tutorials-for-beginners.html: /
  /security/how-can-we-trust-myetherwallet.html: /
  /security/phish-hacks-thefts-and-stolen-funds-due-to-phishing.html: /
  /security/i-cannot-see-the-extended-validation-certificate.html: /
  /tokens/showing-and-loading-tokens.html: /
  /tokens/receiving-tokens.html: /
  /tokens/adding-custom-ethereum-tokens.html: /
  /networks/access-your-musicoin-on-myetherwallet.html: /
  /migration/moving-from-myetherwallet-to-parity.html: /
  /tokens/tokens-ppt.html: /
  /tokens/qtum-are-my-qtum-tokens-safe-in-myetherwallet.html: /
  /send/what-to-do-if-you-sent-to-wrong-address.html: /
  /transactions/error-bad-jump-destination-or-out-of-gas-error.html: /
  /swap/trading-eth-btc-rep-bity-swap.html: /
  /send/creating-wallet-address-to-send-and-receive-eth.html: /
  /send/sending-and-adding-tokens.html: /
  /private-keys-passwords/difference-beween-private-key-and-keystore-file.html: /
  /private-keys-passwords/lost-ethereum-wallet-password.html: /
  /private-keys-passwords/how-to-change-ethereum-account-password-unencrypted-encrypted.html: /
  /private-keys-passwords/parity-phrases-are-no-longer-supported.html: /
  /private-keys-passwords/lost-password-ethereum-presale-wallet-file.html: /
  /offline/sending-offline-with-myetherwallet.html: /
  /posts/faqs/: /en/faqs/
  /posts/categories/: /en/categories/
  /posts/videos/: /en/videos/
  /posts/transactions/what-is-gas/: /en/transactions/what-is-gas/
  /posts/common-issues/unable-to-locate-corresponding-transfer-event-log/: /en/common-issues/unable-to-locate-corresponding-transfer-event-log/
  /posts/diving-deeper/what-happens-if-mew-goes-down/: /en/diving-deeper/what-happens-if-mew-goes-down/
  /posts/security-and-privacy/what-is-a-mnemonic-phrase/: /en/security-and-privacy/what-is-a-mnemonic-phrase/
  /posts/getting-started/how-to-access-your-wallet/: /en/getting-started/how-to-access-your-wallet/
  /posts/transactions/tx-failed-why-was-i-charged/: /en/transactions/tx-failed-why-was-i-charged/
  /posts/diving-deeper/using-mew-as-a-pwa/: /en/diving-deeper/using-mew-as-a-pwa/
  /posts/getting-started/glossary-of-common-terms/: /en/getting-started/glossary-of-common-terms/
  /posts/common-issues/unable-to-connect-with-hardware-wallet/: /en/common-issues/unable-to-connect-with-hardware-wallet/
  /posts/hardware-wallets/using-hardware-wallet-with-custom-node/: /en/hardware-wallets/using-hardware-wallet-with-custom-node/
  /posts/transactions/transaction-not-found-or-pending-forever/: /en/transactions/transaction-not-found-or-pending-forever/
  /posts/common-issues/token-already-exists/: /en/common-issues/token-already-exists/
  /posts/security-and-privacy/what-is-a-keystore-file/: /en/security-and-privacy/what-is-a-keystore-file/
  /posts/transactions/mew-minimum-requirement-for-sending/: /en/transactions/mew-minimum-requirement-for-sending/
  /posts/migration/using-jaxx-with-mew/: /en/migration/using-jaxx-with-mew/
  /posts/diving-deeper/how-to-submit-pull-request/: /en/diving-deeper/how-to-submit-pull-request/
  /posts/getting-started/does-mew-support-other-coins/: /en/getting-started/does-mew-support-other-coins/
  /posts/security-and-privacy/should-i-keep-eth-on-multiple-addresses/: /en/security-and-privacy/should-i-keep-eth-on-multiple-addresses/
  /posts/diving-deeper/how-to-interact-with-multisig-contract/: /en/diving-deeper/how-to-interact-with-multisig-contract/
  /posts/tokens/random-tokens-in-my-wallet/: /en/tokens/random-tokens-in-my-wallet/
  /posts/migration/using-geth-or-mist-with-mew/: /en/migration/using-geth-or-mist-with-mew/
  /posts/common-issues/not-checksummed/: /en/common-issues/not-checksummed/
  /posts/getting-started/difference-between-mew-and-exchange/: /en/getting-started/difference-between-mew-and-exchange/
  /posts/security-and-privacy/pro-tips-how-to-avoid-phishing-scams/: /en/security-and-privacy/pro-tips-how-to-avoid-phishing-scams/
  /posts/transactions/how-to-send-a-transaction/: /en/transactions/how-to-send-a-transaction/
  /posts/hardware-wallets/using-secalot-with-mew/: /en/hardware-wallets/using-secalot-with-mew/
  /posts/migration/moving-from-exchange-to-mew/: /en/migration/moving-from-exchange-to-mew/
  /posts/tokens/how-to-add-custom-token/: /en/tokens/how-to-add-custom-token/
  /posts/getting-started/checking-your-balance/: /en/getting-started/checking-your-balance/
  /posts/hardware-wallets/using-bitbox-with-mew/: /en/hardware-wallets/using-bitbox-with-mew/
  /posts/diving-deeper/does-mew-have-an-api/: /en/diving-deeper/does-mew-have-an-api/
  /posts/common-issues/out-of-gas/: /en/common-issues/out-of-gas/
  /posts/hardware-wallets/using-keepkey-with-mew/: /en/hardware-wallets/using-keepkey-with-mew/
  /posts/transactions/eth-tokens-haven't-shown-up-from-exchange/: /en/transactions/eth-tokens-haven't-shown-up-from-exchange/
  /posts/hardware-wallets/using-ledger-with-mew/: /en/hardware-wallets/using-ledger-with-mew/
  /posts/common-issues/ledger-error-code-5/: /en/common-issues/ledger-error-code-5/
  /posts/security-and-privacy/ensuring-mew-doesnt-give-people-same-address/: /en/security-and-privacy/ensuring-mew-doesnt-give-people-same-address/
  /posts/security-and-privacy/not-recommended/: /en/security-and-privacy/not-recommended/
  /posts/dapps/using_makerdao/: /en/dapps/using_makerdao/
  /posts/common-issues/insufficient-funds/: /en/common-issues/insufficient-funds/
  /posts/security-and-privacy/mnemonic-phrase-password/: /en/security-and-privacy/mnemonic-phrase-password/
  /posts/swap/buy-eth-via-simplex/: /en/swap/buy-eth-via-simplex/
  /posts/offline/offline-mew-looks-weird/: /en/offline/offline-mew-looks-weird/
  /posts/getting-started/back-to-the-basics/: /en/getting-started/back-to-the-basics/
  /posts/networks-and-nodes/how-to-change-networks/: /en/networks-and-nodes/how-to-change-networks/
  /posts/tokens/adding-token-as-a-default/: /en/tokens/adding-token-as-a-default/
  /posts/migration/importing-v2-json-file/: /en/migration/importing-v2-json-file/
  /posts/diving-deeper/does-mew-api-limit-amount-of-requests/: /en/diving-deeper/does-mew-api-limit-amount-of-requests/
  /posts/private-keys-and-passwords/lost-private-key/: /en/private-keys-and-passwords/lost-private-key/
  /posts/hardware-wallets/using-trezor-with-mew/: /en/hardware-wallets/using-trezor-with-mew/
  /posts/getting-started/myetherwallet-an-introduction/: /en/getting-started/myetherwallet-an-introduction/
  /posts/transactions/checking-or-replacing-a-tx-after-sending/: /en/transactions/checking-or-replacing-a-tx-after-sending/
  /posts/mewconnect/mewconnect-101-transfer/: /en/mewconnect/mewconnect-101-transfer/
  /posts/mewconnect/mewconnect-101-connect/: /en/mewconnect/mewconnect-101-connect/
  /posts/mewconnect/mewconnect-101-recover/: /en/mewconnect/mewconnect-101-recover/
  /posts/mewconnect/mewconnect-101-create/: /en/mewconnect/mewconnect-101-create/
  /posts/mewconnect/mewconnect-user-guide/: /en/mewconnect/mewconnect-user-guide/
  /posts/swap/swap-canceled-or-not-completed/: /en/swap/swap-canceled-or-not-completed/
  /posts/mewconnect/mewconnect-secure-enclave/: /en/mewconnect/mewconnect-secure-enclave/
