files:
  - source: /source/_posts/en/**/*.md
    translation: /source/_posts/%two_letters_code%/**/%original_file_name%
  - source: /themes/mew5/languages/en.yml
    translation: /themes/mew5/languages/%two_letters_code%.yml