# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://localhost.com
url: http://kb.mewtest.com/
root: /

# Header
menu:
  Home: /
  Support: mailto:support@myetherwallet.com

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Theme location
theme_desktop: mew-desktop
theme_mobile:  mew-mobile